name: Jira_Trigger_Pipeline

on:
  workflow_dispatch:  # Triggered by external tools from gh cli
  repository_dispatch: # Triggered by external tools like Jira webhooks
    webhookEvent:
      - jira:issue_created
      - jira:issue_updated
      - comment_created
      - comment_updated

jobs:
  process_jira_event:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Process Jira Data
        run: |
          echo "Processing Jira Event..."
          echo "${{ github.event.client_payload }}" > jira_payload.json
