name: Jira_Trigger_Pipeline

on:
  workflow_dispatch:  # Triggered by external tools from gh cli
  repository_dispatch: # Triggered by external tools like Jira webhooks
    types:

jobs:
  generate_and_commit_uml:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      - name: Fetch Jira Issue Data
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          ISSUE_KEY="${{ github.event.client_payload.issue_key }}"
          ISSUE_KEY_VERSION="${{ github.event.client_payload.version }}"
          echo "Fetching data for Jira issue: $ISSUE_KEY and $ISSUE_KEY_VERSION"

          # Call Jira API to get the issue details
          RESPONSE=$(curl -s -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE_KEY")

          # Parse the JIRA_Version custom field
          JIRA_VERSION=$(echo "$RESPONSE" | jq -r '.fields.customfield_10023') # Replace with actual custom field ID
          
          # Print the JIRA_Version field
          echo "JIRA_Version: $JIRA_VERSION"
        
      - name: Generate UML Notation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_uml.py \
            --description "${{ github.event.client_payload.description }}" \
            --output "uml_diagram.puml" \
            --format "plantuml"

      - name: Commit and Push UML Notation
        run: |
          git config --global user.name "varghesepgeorge"
          git config --global user.email "varghese_p_g@yahoo.com"
          git add uml_diagram.puml
          git commit -m "Add UML diagram for ${{ github.event.client_payload.issue_key }}"
          git push
