name: Jira_Trigger_Pipeline

on:
  workflow_dispatch: # Manual trigger for testing
  repository_dispatch: # Triggered by external tools like Jira webhooks
    types: [jira_event]

jobs:
  process_jira_event:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Process Jira Data
        run: |
          echo "Processing Jira Event..."
          echo "${{ github.event.client_payload }}" > jira_payload.json
          python generate_class_diagram.py jira_payload.json

      - name: Commit Diagram
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add class_diagram.png
          git commit -m "Add generated class diagram"
          git push
