name: Process UML Files

on:
  push:
    branches:
      - master
    paths:
      - UML/**  # Trigger only when files in the UML/ folder are modified

jobs:
  process_uml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get modified files
        id: modified_files
        run: |
          git diff --name-only HEAD^ HEAD > modified_files.txt
          echo "files=$(cat modified_files.txt)" >> $GITHUB_ENV

      - name: Process UML Files
        if: success()
        run: |
          python process_uml.py ${{ env.files }}
        env:
          FILES: ${{ env.files }}

      - name: Create and Push Feature Branch
        run: |
          git checkout -b feature/uml-updates
          git add UML/
          git commit -m "Processed UML files"
          git push origin feature/uml-updates
